# Generated by Django 5.2.1 on 2025-05-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_customer_is_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="is_email_verified",
        ),
    ]
