# Generated by Django 5.2.1 on 2025-05-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        ("cart", "0003_rename_property_khaltipaymentlog_property_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="khaltipaymentlog",
            name="property_info",
        ),
        migrations.AddField(
            model_name="khaltipaymentlog",
            name="booking_items",
            field=models.ManyToManyField(
                to="booking.bookingitem", verbose_name="Booking Items"
            ),
        ),
    ]
