# Generated by Django 5.2.1 on 2025-05-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_khaltipaymentlog_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="khaltipaymentlog",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
