# Generated by Django 5.2.1 on 2025-05-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KhaltiPaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pidx", models.CharField(max_length=100, unique=True)),
                ("transaction_id", models.CharField(max_length=100)),
                ("total_amount", models.IntegerField()),
                ("mobile", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
                ("purchase_order_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
