# Generated by Django 5.2.1 on 2025-05-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("property", "0002_remove_property_map_property_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="khaltipaymentlog",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="property.property",
                verbose_name="Property",
            ),
        ),
    ]
