# Generated by Django 5.2.1 on 2025-05-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_khaltipaymentlog_property"),
    ]

    operations = [
        migrations.RenameField(
            model_name="khaltipaymentlog",
            old_name="property",
            new_name="property_info",
        ),
    ]
