# Generated by Django 5.2.1 on 2025-05-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
