# Generated by Django 5.2.1 on 2025-05-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_remove_customer_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
