# Generated by Django 5.2.1 on 2025-05-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_remove_property_map_property_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                ],
                default="available",
                max_length=10,
            ),
        ),
    ]
