# Generated by Django 5.2.1 on 2025-05-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_alter_khaltipaymentlog_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="khaltipaymentlog",
            old_name="created_at",
            new_name="paid_at",
        ),
    ]
