# Generated by Django 5.2.1 on 2025-05-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_created_at_khaltipaymentlog_paid_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khaltipaymentlog',
            options={'verbose_name': 'Payment Log', 'verbose_name_plural': 'Payment Logs'},
        ),
    ]
