# Generated by Django 5.2.1 on 2025-05-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="paid_amount",
            field=models.IntegerField(default=0),
        ),
    ]
